name: Build Spack Environment on macOS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  spack-build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Install Dependencies
        run: |
          brew install git python # Add other dependencies if necessary

      - name: Install Spack
        run: |
          git clone https://github.com/spack/spack.git
          . ./spack/share/spack/setup-env.sh

      - name: Add Spack packages
        run: |
          . ./spack/share/spack/setup-env.sh
          spack env create netcdf
          spack env activate netcdf
          spack add netcdf-c
          spack add netcdf-fortran
          spack add parallel-netcdf
          spack concretize 2<&1 | tee log.concretize

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: log.concretize
          path: ./log.concretize

