name: Spack buildcache build 
on:
  workflow_dispatch:
    inputs:
      os_choice:
        description: 'Select the operating system to run the job on'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - macos-latest

jobs:
  spack-build:
    runs-on: ${{ github.event.inputs.os_choice }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Spack
        uses: spack/setup-spack@v2
      - name: Create Spack Environment 
        run: |
          . /home/runner/work/spack-stack-smoke-tests/spack-stack-smoke-tests/spack/share/spack/setup-env.sh
          spack env activate .
          spack compiler find
      - name: Concretize Spack Environment 
        run: |
          . /home/runner/work/spack-stack-smoke-tests/spack-stack-smoke-tests/spack/share/spack/setup-env.sh
          spack env activate .
          spack concretize 2<&1 | tee log.concretize
          spack install --verbose 2<&1 | tee log.install
          spack -e . buildcache push my-mirror

