name: Spack buildcache build 
on:
  workflow_dispatch:
    inputs:
      os_choice:
        description: 'Select the operating system to run the job on'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
jobs:
  spack-build:
    runs-on: ${{ github.event.inputs.os_choice }}
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Spack
        uses: spack/setup-spack@v2
      - name: Create Spack Environment 
        shell: spack-bash {0}
        run: |
          spack env activate .
          spack compiler find
      - name: Install brew packages 
        shell: spack-bash {0}
        if: runner.os == 'macOS'
        run: |
          brew install krb5
          spack env activate .
          spack external find krb5 --scope=system
      - name: Concretize Spack Environment 
        shell: spack-bash {0}
        run: |
          spack env activate .
          spack external find python --scope=system
          spack external find m4 --scope=system
          spack external find openssl --scope=system
          spack -e . mirror set --oci-username ${{ github.actor }} --oci-password "${{ secrets.ACCESS_TOKEN }}" local-buildcache
          spack concretize 2<&1 | tee log.concretize
          spack install --verbose 2<&1 | tee log.install
          spack -e . buildcache push local-buildcache 

