name: Build Spack Environment on macOS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  spack-build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Spack
        run: |
          git clone https://github.com/spack/spack.git
          . ./spack/share/spack/setup-env.sh

      - name: Create Spack Environment 
        run: |
          . ./spack/share/spack/setup-env.sh
          spack env create netcdf
          spack env activate netcdf
          spack compiler find
          spack compilers
          spack add netcdf-c%apple-clang@15.0.0
          spack add netcdf-fortran%apple-clang@15.0.0
          spack add parallel-netcdf%apple-clang@15.0.0
          spack concretize 2<&1 | tee log.concretize

      - name: Concretize Spack Environment 
        run: |
          . ./spack/share/spack/setup-env.sh
          spack env activate netcdf
          spack concretize 2<&1 | tee log.concretize
      - name: Upload Concretization Logs
        uses: actions/upload-artifact@v3
        with:
          name: log.concretize
          path: ./log.concretize
      - name: Install Spack Environment 
        run: |
          . ./spack/share/spack/setup-env.sh
          spack env activate netcdf
          spack install --verbose 2<&1 | tee log.install
      - name: Upload Concretization Logs
        uses: actions/upload-artifact@v3
        with:
          name: log.install
          path: ./log.install

